language: go
go:
- master

# For forked project
before_install:
- mkdir -p $HOME/gopath/src/github.com/bfirsh/whalebrew
- rsync -az ${TRAVIS_BUILD_DIR}/ $HOME/gopath/src/github.com/bfirsh/whalebrew/
- export TRAVIS_BUILD_DIR=$HOME/gopath/src/github.com/bfirsh/whalebrew
- cd $HOME/gopath/src/github.com/bfirsh/whalebrew

install:
- go get -t ./...
- go get github.com/golang/lint/golint
- go get golang.org/x/tools/cmd/goimports
- go get github.com/mitchellh/gox
script:
- FIXED=$(goimports ./... | wc -l); if [ $FIXED -gt 0 ]; then echo "goimports - $FIXED file(s) not formatted correctly, please run goimports to fix this." && exit 1; fi
- golint ./...
- go test ./...
- script/build
deploy:
  provider: releases
  api_key:
    secure: "GflC3XUZF5HUgC7Rcews+/QDjlfkrY89TFXe7PnGn/XibCH9o9jqzoxQfcVfLQfccfR7T8rcoSSdb0CLY9T0GXq5c3PRHuhupfRYf7hhsVz3mXkuc960v59KNtw4Cdl+t8dzK9WnwcozHKoqJSyhP7D3XZIWzL+o5VWac57aC2Qd258AVHhP7DoJ9yJuWeYNGZh3mdMOiJld7XosHNbaK6g/O7BTF2i/wPVLXiVkd66zrPMuO8xwHhAePKodGC8AKUkT1HDecfBclcJ7e8JJd9iMNuMcdMFndKCqWyg0DfIM5mevtJCR02HR8/9vmFm9R/CmWzau7k/nMGVrBhZW1hb8foxYHR4OGEIQRteb3VQucYAKwVDBdNNvPU/Rg5dVBq/WBKiZ774SyH7huNrg7C0OhSHEHjS45qspOZ1THAt+q+SeJhF5beODTt7c8eUSymG3piej8GQR+R55HLqR3AECAbCelWy+nrqejQRpLSbFrYFNG8a+myhgVNRLzDo4xDdT0iCqJswT50OfrtjLe3O+zQ2Y4Fnp200kWQ9awJGvE/uHfO5VRrEuI3bwgwc8vzGfcG+D8ywfhpNgna+kTGCb2Wip4j8H+9EExHAbTM1S+umXPF2ZZGDeAYN5NPOzMOj76eyp5+vhu6VohuGGDgJy0PxCBWvvuyuAOpbXzWI="
  skip_cleanup: true
  file:
  - "build/whalebrew-Darwin-x86_64"
  - "build/whalebrew-Linux-x86_64"
  on:
    repo: bfirsh/whalebrew
    tags: true
