language: go
go:
- 1.7

install:
- go get -t ./...
- go get github.com/golang/lint/golint

script:
- FIXED=$(go fmt ./... | wc -l); if [ $FIXED -gt 0 ]; then echo "gofmt - $FIXED file(s) not formatted correctly, please run gofmt to fix this." && exit 1; fi
- golint ./...
- go test ./...
