version: "{build}"

os: Windows Server 2012 R2

clone_folder: c:\gopath\src\github.com\bfirsh\whalebrew

environment:
  GOPATH: c:\gopath

install:
  - set PATH=%GOPATH%\bin;%PATH%
  - git submodule update --init --recursive
  - go version
  - go env
  - go get -t ./...
  - go get -u github.com/golang/lint/golint

build_script:
  - golint ./...
  - go test ./...

test: off

deploy: off
